// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package qdrant

type QdrantInput struct {
	// method — the qdrant verb method name (the verb's PRIMARY input field, so
	// `qdrant: health` desugars to {method: "health"}).
	Method string `json:"method"`

	// collection — the target collection for the collection/points/snapshot methods.
	Collection string `json:"collection,omitempty"`

	// size — the vector dimension for collection-create.
	Size int64 `json:"size,omitempty"`

	// distance — the distance metric for collection-create (default cosine).
	Distance string `json:"distance,omitempty"`

	// id — the point id for points-upsert / points-get / points-delete.
	Id int64 `json:"id,omitempty"`

	// vector — the dense vector for points-upsert / points-query.
	Vector []float32 `json:"vector,omitempty"`

	// payload — the payload for points-upsert (scalar values only).
	Payload map[string]any `json:"payload,omitempty"`

	// limit — the result limit for points-query / points-scroll.
	Limit int64 `json:"limit,omitempty"`
}
